### ISSUE TITLE
Design Navbar

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#1]
# Value Statement
As a user of the App, I want to have an attractive colourful and responsive navbar so that users can easily navigate between pages.

# Description

<img width="348" alt="Screenshot 2021-04-21 at 15 53 28" src="https://user-images.githubusercontent.com/72106866/115565516-bab4e980-a2b9-11eb-9171-7684bdc2a029.png">

# Acceptance Criteria

- The NavBar should always be visible.
- It''s positioned as a 'footer'.
- It should be made with React Router.
- It should be responsive.

# Tasks
- [x] Setup Navbar positioning and make it stateless.
- [x] Create components for each nav button.
- [x] Make them responsive.
- [x] Each button has an `onClick` to navigate to another page.

# Complexity
Small
