### ISSUE TITLE
localStorage for Friendlist

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#13]
# Value Statement
As a user of the App, I want to be able to see my friends which I have stored in localStorage render in the friend list so that I can have _more friends_.

# Description

<img width="142" alt="Screenshot 2021-04-28 at 10 34 27" src="https://user-images.githubusercontent.com/72106866/116373074-517b2c00-a80d-11eb-8d95-dfd248b4cf4e.png">

<img width="320" alt="Screenshot 2021-04-28 at 10 37 01" src="https://user-images.githubusercontent.com/72106866/116373489-ad45b500-a80d-11eb-85f7-24b151257b0d.png">

# Acceptance Criteria

- The friend page has a "add new friend" section.
- There will be a add friend form consisting of `name` and `image`.

# Tasks
- [x] create an `add friend` icon.
- [x] create a `form`. 
- [x] The form will pop up on the screen.
- [x] inputs from the form will be sent into localStorage and be displayed in the friend page. 

# Complexity

Medium/High
