### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#15]
# Value Statement
As a user of the app, I want to be able to search for a friend in the search list, after clicking on the search icon and being take to a new page, so that I can see friends in my contacts and filter on search for one.

# Description

<img width="366" alt="Screenshot 2021-04-29 at 09 57 59" src="https://user-images.githubusercontent.com/72106866/116519150-67eabb80-a8d1-11eb-8b86-98a3bd533cd6.png">

# Acceptance Criteria

- The search page has a search bar at the top, and a "Go" button.
- Friends are displayed initially and filtered on search.

# Tasks
- [x] Create a searchbar.
- [x] Create a Go `button`.
- [x] Introduce Storybook.
- [x] Filter on seach.
- [x] Display friends from the localStorage.
- [x] Render the friends in individual divs.

# Complexity

Medium/High
