### ISSUE TITLE
Individual Friend Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#17]
# Value Statement
As a user of the app, I want to view individual friends in the friendslist so that I can see individual information abouut each friend.

# Description

<img width="326" alt="Screenshot 2021-04-30 at 09 36 27" src="https://user-images.githubusercontent.com/72106866/116663552-8c10d000-a997-11eb-81d9-b2ab2c81d495.png">

# Acceptance Criteria

- Clicking on a friend takes the user to the single friend page.
- The friend page will have the name and image of the friend in the header.
- There will be "Review" and "Rating" boxes for the user to edit and "Stats" to read.
- Three icons underneath in a row: Star A Friend, Message, or Remove.
- The nav bar in the footer.

# Tasks
- [x] Clicking on a Friend uses `Link` to navigate to the right page of that dog.
- [x] The route has params `/friends/:id`.
- [x] Recall the LS for `imgSrc` to view.
- [x] Recall the LS for `name` to view.
- [x] The header flex items are `justify-content: left;`
- [x] Recall the LS for `stats` Array to read.
- [x] Recall the LS for `rating` read.
- [x] Recall the LS for `review` read.
- [x] Star A Friend toggles the `isStarred` boolean in LS.
- [x] Message takes the user to the Message Page.
- [x] Remove will return the user to the friends list and remove that friend.

# Complexity

Medium/High
