### ISSUE TITLE
Map page - Initial Setup

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#19]
# Value Statement
As a user of the app, I want to view the map page in the nav bar and see other parks in my area which I can view further information about seperately.

# Description

<img width="351" alt="Screenshot 2021-05-03 at 09 56 08" src="https://user-images.githubusercontent.com/72106866/116853118-cc6d8980-abf5-11eb-8e9c-99724ccf06ea.png">

# Acceptance Criteria

- The Map page contains a map of the Hamburg area.
- The user can select an area and that displays a little breakdown of that park.
- The nav bar in the footer.

# Tasks
- [x] Create a stateless map page.
- [x] Implement MapBox in the code.
- [x] Create Park points based off of coordinates of each one relative to the map.

# Complexity

Medium
