### ISSUE TITLE
Design Central Framework - Profile Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#2]
# Value Statement
As a user of the App, I want to create a responsive flowing design so that users can easily navigate the profile page in a natural way.

# Description

<img width="310" alt="Screenshot 2021-04-26 at 16 33 10" src="https://user-images.githubusercontent.com/72106866/116100555-54f7a180-a6ad-11eb-8650-f0c1fa57aa7d.png">

# Acceptance Criteria

- The profile page will have a picture, a bio, and feedback section and an edit button.
- There is an optional tour button which gives the user an overview of the app.
- There will be a friend count and a rating system also.

# Tasks
- [x] Setup stateless elements
- [x] Setup Component for Global Layout.
- [x] Setup multiple Component files in a central `components` folder.
- [x] Set the text styling.
- [x] Set a default image.
- [x] Use a `clip-path` where nessessary.
- [x] Define color scheme in the `:root` folder.

# Complexity

Medium
