### ISSUE TITLE
Single Map Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#22]
# Value Statement
As a user of the app, I want to view individual parks on the map so as to see updates and left notes for others.

# Description

<img width="270" alt="Screenshot 2021-05-03 at 21 34 19" src="https://user-images.githubusercontent.com/72106866/116923769-539f1980-ac57-11eb-8d4a-3e8b1e7e47be.png">

# Acceptance Criteria

- The title must be the selected Park.
- There are updates from others about that specific park.
- The user can lleave a note for others.
- The nav bar in the footer.

# Tasks
- [x] Create a stateless page.
- [x] Add the title to the top of the page through a a `filter` and `map`method.
- [x] The nav bar is always visible.
- [x] Create the basic components for the page.
- [x] Send the notes into LS for that particular park.
- [x] Retrieve the notes on refresh with LS for park-specific pages.  

# Complexity

Medium/High
