### ISSUE TITLE
red notification

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#24]
# Value Statement
As a user of the app, I want to know which park I have starred so that I may find them easier.

# Description

<img width="443" alt="Screenshot 2021-05-04 at 19 19 22" src="https://user-images.githubusercontent.com/72106866/117043531-a4714980-ad0d-11eb-8f19-acaa1d21689f.png">

# Acceptance Criteria

- The notification must be red.
- The dot is easy to see.
- The starred Parks only have a red dot, the others do not.

# Tasks
- [x] Use a React Icon. 
- [x] Use `position: absolute;`.
- [x] Have a ternary operator for the class so  that one is hidden and one is not.
- [x] Position correctly under the tree.

# Complexity

Low
