### ISSUE TITLE
add IDs to the friends Array

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#31]
# Value Statement
As a user with friends in LocalStorage, I want to be able to implement IDs for each friend that is saved.

# Description

<img width="156" alt="Screenshot 2021-05-06 at 10 05 01" src="https://user-images.githubusercontent.com/72106866/117263423-8a8d4f00-ae52-11eb-8001-c6738cbdd082.png">

# Acceptance Criteria

- Each ID must be unique.

# Tasks
- [x] create a function for `id` in `itemStorage.js`.
- [x] `id` must use `Date.now`.
- [x] Implement ID across the whole app. 

# Complexity

Medium/High
