### ISSUE TITLE
Link Profile Page to LS user and Render

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#34]
# Value Statement
As a new user to the app, I want my create profile page to render the information into the Profile Page.

# Description

<img width="392" alt="Screenshot 2021-05-08 at 00 12 13" src="https://user-images.githubusercontent.com/72106866/117513459-0c37c680-af92-11eb-9ce8-4346b4ba3cfa.png">

# Acceptance Criteria

- Picture is slightly modified.
- Bio and Name are specific to the User.
- Profile is rendered from the User's choice.

# Tasks
- [x] Make use of LocalStorage.
- [x] `useEffect` on mount.
- [x] Dynamically render `name`, `bio` and `picture`.
- [x] `border-radius: 50%;` on the profile picture.
- [x] `useState` for each of the three dynamically rendered values. 

# Complexity

Medium
