### ISSUE TITLE
Log In Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#38]
# Value Statement
As a first time user of the app, I want to create a login page where the user can signup for an account and then sign in to their account.

# Description
<img width="270" alt="Screenshot 2021-05-10 at 10 40 08" src="https://user-images.githubusercontent.com/72106866/117631021-19b0a480-b17c-11eb-9cf3-9d6196d8bac9.png">

# Acceptance Criteria

- Walkies & Talkies logo at the top.
- Username and Password Inputs.
- Login and Signup buttons.

# Tasks
- [x] Create a `form`.
- [x] Username has `type="text"`.
- [x] Password has `type="password"`.
- [x] Register button takes the user to a Register Page.

# Complexity

Medium
