### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#39]
# Value Statement
As a first time user of the app, I want to create a register page so that the user can set up an account to return to on each visit.

# Description

<img width="269" alt="Screenshot 2021-05-10 at 10 39 28" src="https://user-images.githubusercontent.com/72106866/117630947-01d92080-b17c-11eb-967c-59179729a842.png">

# Acceptance Criteria

- Walkies & Talkies logo at the top.
- Username and Password Inputs.
- Confirm Password input.
- Register button.

# Tasks
- [x] Create a `form`.
- [x] Username has `type="text"`.
- [x] Password has `type="password"`.
- [x] If the two password inputs match, then the password is verified.
- [x] Save the account to MongoDB Compass.
- [x] Sign Up button takes the user back to the log in page.

# Complexity

Medium/High
