### ISSUE TITLE
User Journey and Integration with MongoDB Compass - Logging In

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#42]
# Value Statement
As a new or returning user to the app, I want to verify that all user journeys are integrated so that the user can have a flowing experience through the app, with changes pushed to their personal data collection in MongoDB Compass.

# Description

<img width="449" alt="Screenshot 2021-05-10 at 17 00 39" src="https://user-images.githubusercontent.com/72106866/117680223-40d59900-b1b1-11eb-906c-6800bcb49567.png">

# Acceptance Criteria

- New Users are taken to the Register Page.
- Returning Users login to their account and see saved data on load.

# Tasks
- [x] Log In button takes the user to the Create a Profile page if new, and the Profile Page if the User is returning.
- [x] New users without usernames and passwords go to register page to create one.
- [x] Send information from Create Page to Compass.

# Complexity

High
