### ISSUE TITLE
Refactor code, clean up - Create Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#48]
# Value Statement
As a user seeing the create page for the first time, I want to create a flowing form that is responsive and easy to read so that the user can enjoy the experience of filling out their profile details.

# Description

<img width="464" alt="Screenshot 2021-05-12 at 11 16 25" src="https://user-images.githubusercontent.com/72106866/117950464-7f836480-b313-11eb-9f18-cc28286f137f.png">

# Acceptance Criteria

- The form should be styled.
- The code for this page should be tidied with components and imported functions used where possible.

# Tasks
- [x] Create a better structured form with `display: grid;`.
- [x] Move large chunks of code to components.
- [x] Where applicable, import functions.
- [x] Refactor where possible.

# Complexity
Medium/Low
