### ISSUE TITLE
Cover Design

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#5]
# Value Statement
As a newcomer to the App, I want to have a landing page that the user finds so that they have a good feel for the app to follow.

# Description

# Acceptance Criteria

- The colours will be attractive and dynamic.
- Font must be Cookie.
- The Page must be the initial landing page.

# Tasks
- [x] Setup Anchor for the cover page to navigate to the profile page.
- [x] Define color scheme from the `:root` folder.
- [x] Create rough shapes for design.

# Complexity
Small
