### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#55]
# Value Statement
As a user of the App, I want to have an efficient fast running app, that is light in weight so that my eperience is not slowed down by heavy memory.

# Acceptance Criteria

- Make components where possible.
- Cut down and clean up code.

# Tasks
- [x] Map Component. 
- [x] Delete Commented code.
- [x] Delete console logs.
- [x] AddButton Components.
- [x] Delete FileUploader.
- [x] Delete unnecessary image files.
- [x] Create fail state page Component.
- [x] Move Stories to a Stories folder.
- [x] LogIn Form Component.
- [x] Register Form Component.

# Complexity
Medium
