### ISSUE TITLE
Fix Tour and Edit Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#61]
# Value Statement
As a user of the App, I want to be able to edit my bio and picture so that I can update my profile page.

# Acceptance Criteria

- Pressing the photo button gives the user the chancce to update their photo.
- Pressing the pen gives the user the oppertunity to update the bio.

# Tasks
- [x] `onClick` for functions to update the photo and bio.
- [x] Create a pop up display for the edit bio section.
- [x] `save` pushes changes to localStorage.

# Complexity
Medium
