### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#63]
# Value Statement
As a user of the app, I want to be able to use a responsive light app so that my experience is better.

# Acceptance Criteria

- Refactor the code into more organised chunks.

# Tasks
- [x] Custom hooks for Parks, Friends and User.
- [x] Refactor all code to resond to above hooks.
- [x] Tidy up server.js
- [x] Tidy up `stories`
- [x] Button consistency across the app

# Complexity
Medium
