### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#67]
# Value Statement
As a user of the app, I want to have a lightweight responsive app that isnt slowed down by unnessesary code, so that my experience is better served.

# Acceptance Criteria

- Fix issues across the app.

# Tasks
- [x] Create a condition render of the review in the SingleDog page.
- [x] Create a condition render of the ratings in the SingleDog page.
- [x] Create a condition render of the stats in the SingleDog page.
- [x] Push the `options` to end of the page in singleDog if the page is empty.
- [x] Fix edit page so that uploading a picture *or* writing in the bio is optional. 
- [x] Fix `upload button` on the Create Page.
- [x] Fix the `counter` so the Enter button doesn't create an issue.
- [x] Delete bio in `addFriendButton` and all rules involved.
- [x] Delete unused class names.
- [x] Fix `save` button so that if no editing is made, a notification is given.
- [x] Move the `parks.json` to somewhere more convenient.

# Complexity
Medium
