### ISSUE TITLE
Cypress Checks - Logging In

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#72]
# Value Statement
As a developer of the app, I want to test with Cypress so that I can ensure that everything is working smoothly.

# Acceptance Criteria

- Set up Cypress across the app to test my app.

# Tasks
- [x] Implement Cypress.
- [x] Test logging in with Cypress.
- [x] Create a test using Cypress.
- [x] Check Cypress functionality.

# Complexity
Medium/High
