### ISSUE TITLE
CSS - Styling different pages

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#77]
# Value Statement
As a user of the app, I want to have a smooth experiencce and enjoy the CSS so that I may be a returning user.

# Acceptance Criteria

- Style CSS where nessesary.

# Tasks
- [x] Correct the bio bubble so the text is correctly aligned.
- [x] render a conditional message on dog page when no info is supplied.
- [x] Clean up the park page, style and add delete functionality for notes.

# Complexity
Medium/High
