### ISSUE TITLE
Add IDs to parks

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#81]
# Value Statement
As a developer of the app, I want to timplement IDs to the park.json so that each park has a unique ID identifier.

# Acceptance Criteria

- Set up IDs in the Park.json.
- Implement across the app.

# Tasks
- [x] Implement IDs in `park.json`.
- [x] Replace the coordiante ID with the new IDs.
- [x] Update the localStorage functions.

# Complexity
Medium/Low
