### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#82]
# Value Statement
As a user of the app, I want to have some animations on the app so that the experience is visually pleasing to me.

# Acceptance Criteria

- Implement animations across the app where necessary. 

# Tasks
- [x] Apply animations to login page.
- [x] Apply animations to profile page.
- [x] Apply animations to friends page.
- [x] Apply animations to search page.
- [x] Apply animations to singlePark page.
- [x] Apply animations to Map page.
- [x] Keep consistency with button animations.
# Complexity
Medium
