### ISSUE TITLE
Design Central Framework - Friend Page

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#9]
# Value Statement
As a user of the App, I want to create a responsive flowing design so that users can easily navigate the friends page in a natural way.

# Description

<img width="320" alt="Screenshot 2021-04-27 at 15 47 24" src="https://user-images.githubusercontent.com/72106866/116252446-df083e80-a76f-11eb-96fa-eb2bcf2d03b5.png">

# Acceptance Criteria

- The friend page will have a search icon, the friends in a cloud formation and a background image of some kind.
- Clicking on a friend takes you to their respective pages.

# Tasks
- [x] Setup stateless elements
- [x] Setup multiple Component files in a central `components` folder.
- [x] Set the text styling.
- [x] Set a background image.
- [x] Use the SVGs from Adobe XD for the clouds.
- [x] Clouds can repeat after 5 shapes.
- [x] use random images of dogs for the friend icons.

# Complexity

Medium
