### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#92]
# Value Statement
As a user of the app, I want to have a responsive app that responds to the viewport of my device, up to iPad. 

# Acceptance Criteria

- Set up Media Queries where necessary.
- Implement across the app.

# Tasks
- [x] Fix Create Profile page.
- [x] Fix profile and edit profile pages. 
- [x] Tweak Noteworthy sign.
- [x] Fix Login layout.
- [x] Fix Single Park.
- [x] Fix navigation.   

# Complexity
Medium
