### ISSUE TITLE
Input Requirements - Register / Create Profile

### ISSUE THREAD

**Issue by hugh-burgess** [hugh-burgess/CapstoneNF2021#93]
# Value Statement
As the creator of the app, I want to have a required fields so that there is no mistake of empty rendered fields in the profile page and internal database.

# Acceptance Criteria

- Set up input requirements on the register and create profile page.

# Tasks
- [x] Username must be required.
- [x] Bio must be required.
- [x] Name must be required. 

# Complexity
Low
